### ISSUE TITLE
Public copyright infringement is not cool. Please keep it private.

### ISSUE THREAD

**Issue by rednoah** [mobeigi/filebot#1]
You're welcome to maintain your own personal fork, for your own purposes. But at least make it private and don't advertise the fact. Don't know. Don't care. But if it's public, with pre-built binaries attached, then that's just not cool.

**Comment by mobeigi** [comment]
No copyright infringement is taking place here. This is just a fork of a previously open sourced repo.

**Comment by rednoah** [comment]
You didn't write the code. You didn't contribute to the code. The existence of an open-source repository does not automatically give you the copyright to the code. You only have the rights that the original license bestows, and it explicitly disallows your behaviour, i.e. publishing binary builds.
